#!usr/bin/python3
from subprocess import call
import os,sys

call(['sudo', 'apt', 'update'])
call(['sudo', 'apt', 'upgrade'])
call(['sudo', 'apt', 'install', 'docker.io'])

def crear():
        call(['sudo', 'docker', 'build', '-t', '16/product-page', '.'])
        os.system('sudo docker run -it --name 16-productpage -p 9080:9080 --env GROUP_NUMBER=$

def arrancar():
        os.system('sudo docker run -it -p 9080:9080 --env GROUP_NUMBER=16 16/product-page')

def liberar():
        os.system('yes | sudo docker container prune')

param = sys.argv

if param[1] == "arrancar":
        arrancar()
if param[1] == "crear":
        crear()
if param[1] == "liberar":
        liberar()